/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Databases.DB;
import Databases.Table.SupplierManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nipun
 */
public class AddSupplierFrame extends javax.swing.JFrame {

    private static final String CODEUSEDERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මෙම කේතය දැනටමත් භාවිතා කර ඇත!"
            + "</font></p></html>";

        private static final String COMPANYUSEDERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මෙම ආයතනය දැනටමත් භාවිතා කර ඇත!"
            + "</font></p></html>";
        
       private static final String REQUIREDALLDETAILSERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">කරුණාකර තරු ලකුණ දමා ඇති සියලු විස්තර ලබා දෙන්න!"
            + "</font></p></html>";
       
       private static final String SUPPLIERADDED
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">සැපයුම්කරුව සාර්ථකව ඇතුලත් කරන ලදී."
            + "</font></p></html>";
       
       
         private static final String TRYAGAINERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">ක්‍රියාවලිය සම්පූර්ණ නැත. නැවත උත්සාහ කරන්න."
            + "</font></p></html>";
         
          private static final String WRONGNUMBER
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">වැරදි දූරකථන අංකයකි!"
            + "</font></p></html>";
       
       
    boolean add = false;
    
    boolean isEditing = false;
    
    private String addedCode = "";
    private String addedCompany = "";

    /**
     * Creates new form AddSupplierFrame
     */
    public AddSupplierFrame() {
        initComponents();

//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        addBtn.setText("<html> ඇතුලත් <br> කරන්න</html>");
        cancelBtn.setText("<html>  අවලංගු <br> කරන්න</html>");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        clearFeilds();
    }

    private static AddSupplierFrame instance;

    public static synchronized AddSupplierFrame getInstance() {
        if (instance == null) {
            instance = new AddSupplierFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contact2 = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        agentFname = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        agentLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(717, 490));
        setMinimumSize(new java.awt.Dimension(717, 490));
        setPreferredSize(new java.awt.Dimension(717, 490));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(234, 249, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setText("නියෝජිතයාගේ මුල් නාමය*");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setText("කේතය*");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 30));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel4.setText("දූරකථන අංකය1*");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 30));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setText(" දූරකථන අංකය2");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        contact2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        contact2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contact2FocusLost(evt);
            }
        });
        contact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact2KeyTyped(evt);
            }
        });
        jPanel3.add(contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 400, 30));

        code.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeFocusLost(evt);
            }
        });
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });
        jPanel3.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 400, 30));

        agentFname.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        agentFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agentFnameKeyTyped(evt);
            }
        });
        jPanel3.add(agentFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 400, 30));

        contact1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        contact1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contact1FocusLost(evt);
            }
        });
        contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact1KeyTyped(evt);
            }
        });
        jPanel3.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 400, 30));

        agentLname.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        agentLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agentLnameKeyTyped(evt);
            }
        });
        jPanel3.add(agentLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 400, 30));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel5.setText("නියෝජිතයාගේ අවසන් නාමය");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        companyName.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        companyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFocusLost(evt);
            }
        });
        companyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                companyNameKeyTyped(evt);
            }
        });
        jPanel3.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 400, 30));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel6.setText(" ආයතනය නාමය*");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 370));

        jPanel4.setBackground(new java.awt.Color(234, 249, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 249, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        addBtn.setText("ඇතුලත් කරන්න");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 3, -1, 45));

        cancelBtn.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cancelBtn.setText(" අවලංගු කරන්න");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 3, -1, 45));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 680, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        if (!code.getText().toString().isEmpty() && !code.getText().toString().isEmpty() && !agentFname.getText().toString().isEmpty() && !companyName.getText().toString().isEmpty() && !contact1.getText().toString().isEmpty()) {

            if (add) {
                
                 if (contact1.getText().length() >= 9){

                     if (contact2.getText().length() >= 9 || contact2.getText().isEmpty()){
                         
                Databases.Beans.Supplier supplier = new Databases.Beans.Supplier()
                        .setCode(code.getText()).setAgentFname(agentFname.getText()).setAgentLname(agentLname.getText()).setCompany(companyName.getText()).setTp1(contact1.getText()).setTp2(contact2.getText());

                if(!isEditing){
                if (SupplierManager.addSupplier(supplier)) {
                    this.dispose();
                    Supplier.getInstance().loadTable();
                    clearFeilds();
                } else {
                    JOptionPane.showMessageDialog(this, TRYAGAINERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
                }
                }else{
                    supplier.setOldCode(addedCode);
                       if (SupplierManager.editSupplier(supplier)) {
                    this.dispose();
                    Supplier.getInstance().loadTable();
                    clearFeilds();
                } else {
                    JOptionPane.showMessageDialog(this, TRYAGAINERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
                }
                }
         
                 }
                 }
            }
        }else{
              JOptionPane.showMessageDialog(this, REQUIREDALLDETAILSERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

        if (Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();
        }

        if ((code.getText().length() == 5)) {
            evt.consume();
        }
    }//GEN-LAST:event_codeKeyTyped

    private void agentFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agentFnameKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_agentFnameKeyTyped

    private void agentLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agentLnameKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_agentLnameKeyTyped

    private void companyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyNameKeyTyped

    }//GEN-LAST:event_companyNameKeyTyped

    private void contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

        if ((contact1.getText().length() == 10)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_contact1KeyTyped

    private void contact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

        if ((contact2.getText().length() == 10)) {
            evt.consume();
        }
    }//GEN-LAST:event_contact2KeyTyped

    private void codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeFocusLost
        if (SupplierManager.isCodeExits(code.getText()) && !code.getText().equals(addedCode)) {
            add = false;
            JOptionPane.showMessageDialog(this, CODEUSEDERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
            code.selectAll();
            code.grabFocus();

        } else {
            add = true;
        }
    }//GEN-LAST:event_codeFocusLost

    private void contact1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contact1FocusLost
        if (contact1.getText().length() < 9 && contact1.getText().length() != 0) {
             JOptionPane.showMessageDialog(this, WRONGNUMBER, "වැරදි", JOptionPane.ERROR_MESSAGE);
            contact1.grabFocus();
        }
    }//GEN-LAST:event_contact1FocusLost

    private void contact2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contact2FocusLost
      if (contact2.getText().length() < 9 && contact2.getText().length() != 0) {
             JOptionPane.showMessageDialog(this, WRONGNUMBER, "වැරදි", JOptionPane.ERROR_MESSAGE);
            contact2.grabFocus();
        }
    }//GEN-LAST:event_contact2FocusLost

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
         this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void companyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusLost
       if (SupplierManager.isCompanyExits(companyName.getText()) && !companyName.getText().equals(addedCode)) {
            add = false;
            JOptionPane.showMessageDialog(this, COMPANYUSEDERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
            companyName.selectAll();
            companyName.grabFocus();

        } else {
            add = true;
        }
    }//GEN-LAST:event_companyNameFocusLost

    
    public void clearFeilds(){
        isEditing = false;
        code.setText(null);
        agentFname.setText(null);
        agentLname.setText(null);
        companyName.setText(null);
        contact1.setText(null);
        contact2.setText(null);
        code.grabFocus();
        code.selectAll();
    }
    
    
    public void loadAddedSupplier(String addedCode){
        this.addedCode = addedCode;
        clearFeilds();
        ResultSet result = SupplierManager.getSupplierFromCode(addedCode);
        
        try {
            while(result.next()){
                code.setText(result.getString("code"));
                agentFname.setText(result.getString("agent_fname"));
                agentLname.setText(result.getString("agent_lname"));
                addedCompany = result.getString("company");
                companyName.setText(addedCompany);
                contact1.setText(result.getString("contact_number1"));
                contact2.setText(result.getString("contact_number2"));
            }
        } catch (SQLException ex) {
            DB.processException(ex);
        }
        
            code.grabFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField agentFname;
    private javax.swing.JTextField agentLname;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField code;
    private javax.swing.JTextField companyName;
    private javax.swing.JTextField contact1;
    private javax.swing.JTextField contact2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
