/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Databases.DB;
import Databases.Table.UserManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author nipun
 */
public class Login extends javax.swing.JFrame {

    private static final String WRONGUSERNAMEERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">ගිණුමේ නම නැවත පරික්ෂා කරන්න!"
            + "</font></p></html>";

    private static final String WRONGPASSWORDERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මුර පදය නැවත පරික්ෂා කරන්න!"
            + "</font></p></html>";

    private static final String ACCOUNTDEACTIVATEDMSG
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">ඔබගේ ගිණුම අක්‍රිය කර ඇත."
            + "</font></p></html>";

    private static final String THREEATTEMPSFAILED
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">උත්සාහයන් තුනම අසාර්ථක විය; ඔබගේ ගිණුම අක්‍රිය කර ඇත."
            + "</font></p></html>";

    private static final String NOUSERNAMEMSG
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">කරුණාකර ගිණුමේ නම ඇතුලත් කරන්න!"
            + "</font></p></html>";

    private static final String WRONGANSWERSERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">ඔබේ පිළිතුරු වැරදි. නැවත පරික්ෂා කරන්න!"
            + "</font></p></html>";

    private static final String PASSWORDNOTMATCHERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මුරපදය නොගැලපේ!"
            + "</font></p></html>";

    private static final String REQUIREDALLDETAILSERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">කරුණාකර සියලු විස්තර ලබා දෙන්න!"
            + "</font></p></html>";

    private static final String PASSWORDRESETMSG
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මුරපදය සාර්ථකව වෙනස් විය."
            + "</font></p></html>";

    private static final String PASSWORDCHARACTERERROR
            = "<html><p><font color=\"#000\" "
            + "size=\"4\" face=\"Nirmala UI\">මුර පදයේ අක්ෂර ගණන 5ට වැඩි වියයුතුයි!"
            + "</font></p></html>";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fogetPassword = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        question1 = new javax.swing.JLabel();
        answer1 = new javax.swing.JTextField();
        answer2 = new javax.swing.JTextField();
        question2 = new javax.swing.JLabel();
        answer3 = new javax.swing.JTextField();
        question3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        resetPassword = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        newConfirmPassword = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        fogetPassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 249, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        question1.setText("බල්ලගේ නම මොකක්ද?");
        jPanel2.add(question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 350, 30));

        answer1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel2.add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 310, 30));

        answer2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel2.add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 310, 30));

        question2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        question2.setText("බල්ලගේ නම මොකක්ද?");
        jPanel2.add(question2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 350, 30));

        answer3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel2.add(answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 310, 30));

        question3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        question3.setText("බල්ලගේ නම මොකක්ද?");
        jPanel2.add(question3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 350, 30));

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("තහවරු කරන්න");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 40));

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 40));

        fogetPassword.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 410));

        jPanel3.setBackground(new java.awt.Color(234, 249, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel5.setText("අලුත් මුර පදය");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        newPassword.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        newPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordFocusLost(evt);
            }
        });
        newPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPasswordKeyTyped(evt);
            }
        });
        jPanel3.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 260, 30));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel10.setText("නැවත අලුත් මුර පදය");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        newConfirmPassword.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        newConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newConfirmPasswordFocusLost(evt);
            }
        });
        newConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newConfirmPasswordKeyTyped(evt);
            }
        });
        jPanel3.add(newConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 260, 30));

        jButton6.setBackground(new java.awt.Color(0, 204, 0));
        jButton6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("වෙනස් කරන්න");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 40));

        jLabel11.setBackground(new java.awt.Color(0, 204, 0));
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 40));

        javax.swing.GroupLayout resetPasswordLayout = new javax.swing.GroupLayout(resetPassword.getContentPane());
        resetPassword.getContentPane().setLayout(resetPasswordLayout);
        resetPasswordLayout.setHorizontalGroup(
            resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        resetPasswordLayout.setVerticalGroup(
            resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(234, 249, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setText("මුර පදය අමතක උනාද?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setText("ගිනුම් නම ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 30));

        username.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 250, 30));

        password.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ඇතුල් වන්න");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setText("මුර පදය");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText(" නවත්වන්න");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, 30));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, 30));

        jLabel8.setBackground(new java.awt.Color(0, 204, 0));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 130, 30));

        jPanel4.setBackground(new java.awt.Color(79, 195, 109));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pamuditha Stores");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 220, 101));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ගිණුමට පිවිසෙන්න");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        String name = username.getText();

        if (!name.isEmpty()) {

            try {
                ResultSet res = UserManager.getDeactiveUserNameFromName(name);
                if (!res.next()) {
                    
                    if (UserManager.isUserNameExits(name)) {
                        loadQuestions(name);
                        fogetPassword.pack();
                        fogetPassword.setLocationRelativeTo(null);
                        fogetPassword.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, WRONGUSERNAMEERROR, "අවවාදයයි", JOptionPane.WARNING_MESSAGE);
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, ACCOUNTDEACTIVATEDMSG, "දැනුම්දීමයි", JOptionPane.WARNING_MESSAGE);
                    username.grabFocus();
                    username.selectAll();
                    password.setText(null);
                }
            } catch (SQLException ex) {
               ex.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(this, NOUSERNAMEMSG, "අවවාදයයි", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!username.getText().isEmpty() && !String.valueOf(password.getPassword()).isEmpty()) {
            login();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPasswordKeyTyped
        if (Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_newPasswordKeyTyped

    private void newConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newConfirmPasswordKeyTyped
        if (Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_newConfirmPasswordKeyTyped

    private void newConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newConfirmPasswordFocusLost
        String pass1 = String.valueOf(newPassword.getPassword());
        String pass2 = String.valueOf(newConfirmPassword.getPassword());

        if (!pass2.isEmpty()) {

            if (!pass1.equals(pass2)) {
                JOptionPane.showMessageDialog(resetPassword, PASSWORDNOTMATCHERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
                newPassword.setText(null);
                newConfirmPassword.setText(null);
                newPassword.grabFocus();
            }

        }
    }//GEN-LAST:event_newConfirmPasswordFocusLost

    private void newConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newConfirmPasswordFocusGained
        String pass1 = String.valueOf(newPassword.getPassword());
        if (pass1.isEmpty()) {
            newPassword.grabFocus();
        }
    }//GEN-LAST:event_newConfirmPasswordFocusGained

    private void newPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusLost
        String pass1 = String.valueOf(newPassword.getPassword());
        if (!pass1.isEmpty()) {
            if (pass1.length() <= 5) {
                JOptionPane.showMessageDialog(resetPassword, PASSWORDCHARACTERERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
                newPassword.grabFocus();
            }
        }
    }//GEN-LAST:event_newPasswordFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (answer1.getText().equalsIgnoreCase(a1) && answer2.getText().equalsIgnoreCase(a2) && answer3.getText().equalsIgnoreCase(a3)) {
            fogetPassword.dispose();
            resetPassword.pack();
            resetPassword.setLocationRelativeTo(null);
            resetPassword.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(fogetPassword, WRONGANSWERSERROR, "වැරදි", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (!String.valueOf(newPassword.getPassword()).isEmpty() && !String.valueOf(newConfirmPassword.getPassword()).isEmpty()) {

            String pass1 = String.valueOf(newPassword.getPassword());
            String pass2 = String.valueOf(newConfirmPassword.getPassword());
            if (pass1.equals(pass2)) {
                try {
                    String encripedPass = Encription.Encript.encript(pass1);

                    if (UserManager.resetPasswordFromName(encripedPass, uName)) {
                        JOptionPane.showMessageDialog(resetPassword, PASSWORDRESETMSG);
                        resetPassword.dispose();
                        password.grabFocus();
                    }
                } catch (Exception ex) {
                    DB.processException(ex);
                }
            } else {
                JOptionPane.showMessageDialog(resetPassword, PASSWORDNOTMATCHERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
                newPassword.setText(null);
                newConfirmPassword.setText(null);
                newPassword.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(resetPassword, REQUIREDALLDETAILSERROR, "වැරදි", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private int counter = 0;

    private String uName;
    private String a1, a2, a3;

    private void login() {

        try {

            Loggers.Log4JTest.exceptionLogger();
            Logger logger = Logger.getLogger("Login");

            String usernameTxt = username.getText();
            String passwordTxt = Encription.Encript.encript(String.valueOf(password.getPassword()));

            ResultSet result = UserManager.getActiveUserNameFromName(usernameTxt);

            if (result.next()) {
                counter++;

                ResultSet rs = UserManager.getActiveUserFromCredential(usernameTxt, passwordTxt);

                if (rs.next()) {
                    long currentTime = new java.util.Date().getTime();
                    java.sql.Timestamp currentStamp = new java.sql.Timestamp(currentTime);

                    UserManager.addLoginLog(rs.getString("iduser"), currentStamp);

                    logger.info(usernameTxt + " loging to system");
//                    new Main().setVisible(true);
                    new Loading(rs.getString("iduser")).setVisible(true);
                    this.dispose();

                } else {
                    logger.warn(usernameTxt + " trying to login with password " + Encription.Encript.decript(passwordTxt));
                    JOptionPane.showMessageDialog(this, WRONGPASSWORDERROR, "වැරදි", JOptionPane.WARNING_MESSAGE);
                    password.grabFocus();
                    password.selectAll();
                    if (counter == 3) {
                        UserManager.deactivateUserFromUsername(usernameTxt);
                        logger.info(usernameTxt + " user account has been deactivated!");
                        JOptionPane.showMessageDialog(this, THREEATTEMPSFAILED, "අවවාදයයි", JOptionPane.WARNING_MESSAGE);
                        dispose();
                    }

                }
            } else {
                ResultSet res = UserManager.getDeactiveUserNameFromName(usernameTxt);
                if (res.next()) {
                    JOptionPane.showMessageDialog(this, ACCOUNTDEACTIVATEDMSG, "දැනුම්දීමයි", JOptionPane.WARNING_MESSAGE);
                    logger.info(res.getString("username") + " user account has been deactivated!");
                    username.grabFocus();
                    username.selectAll();
                    password.setText(null);
                } else {
                    logger.warn("Someone trying to login with username " + usernameTxt);
                    JOptionPane.showMessageDialog(this, WRONGUSERNAMEERROR, "වැරදි", JOptionPane.WARNING_MESSAGE);
                    username.grabFocus();
                    username.selectAll();
                    password.setText(null);
                }
            }
        } catch (Exception e) {
            DB.processException(e);
        }
    }

    private void loadQuestions(String username) {

        try {
            uName = username;
            ResultSet result = UserManager.getSelecteQ_AFromUsername(username);

            while (result.next()) {
                if (result.getRow() == 1) {
                    question1.setText(result.getString("recovery_question"));
                    a1 = result.getString("answer");
                } else if (result.getRow() == 2) {
                    question2.setText(result.getString("recovery_question"));
                    a2 = result.getString("answer");
                } else if (result.getRow() == 3) {
                    question3.setText(result.getString("recovery_question"));
                    a3 = result.getString("answer");
                }
            }

        } catch (SQLException ex) {
            DB.processException(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1;
    private javax.swing.JTextField answer2;
    private javax.swing.JTextField answer3;
    private javax.swing.JDialog fogetPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField newConfirmPassword;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JDialog resetPassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
